name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: NPM Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Check types
        run: npm run check:types
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
